name: Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.2.4 

      - name: Run tests
        run: deno test 

